In [5]:
import cv2, random

In [2]:
cv2.__version__

'4.1.0'

In [6]:
image = cv2.imread("C:/Users/Business Intelli/Desktop/cats vs dogs/train/dogs/dog.109.jpg", -1)

print(image)

[[[ 72  97 123]
  [ 69  94 120]
  [ 66  91 117]
  ...
  [ 38  13   9]
  [ 35  10   6]
  [ 32  10   5]]

 [[ 57  81 109]
  [ 56  81 107]
  [ 57  81 109]
  ...
  [ 44  19  15]
  [ 38  16  11]
  [ 35  13   8]]

 [[ 52  76 106]
  [ 53  77 105]
  [ 56  80 110]
  ...
  [ 39  17  12]
  [ 33  13   8]
  [ 31  11   6]]

 ...

 [[ 71  87  94]
  [ 69  85  92]
  [ 69  85  92]
  ...
  [ 45  57  61]
  [ 45  57  61]
  [ 47  59  63]]

 [[ 72  87  96]
  [ 72  87  96]
  [ 71  88  97]
  ...
  [ 45  56  60]
  [ 44  55  59]
  [ 47  58  62]]

 [[ 75  90  99]
  [ 76  91 100]
  [ 77  94 103]
  ...
  [ 49  60  64]
  [ 48  59  63]
  [ 50  61  65]]]


In [4]:
image_size = image.shape[0:2]
image_size

(268, 439)

In [10]:
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
print('original image shape:', image.shape)

original image shape: (268, 439, 3)


In [7]:
w, h = image.shape[1], image.shape[0]

In [8]:
#defining random point inside image
def rand_pt(mult = 1.):
    return(random.randrange(int(w*mult)),
          random.randrange(int(h*mult)))


In [9]:
#drawing circles
cv2.circle(image, rand_pt(), 90, (255, 0, 0))
cv2.circle(image, rand_pt(), 5, (255, 0, 0), cv2.FILLED)
cv2.circle(image, rand_pt(), 40, (255, 85, 85), 2)
cv2.circle(image, rand_pt(), 90, (255, 170, 170), 2, cv2.LINE_AA)


array([[[ 72,  97, 123],
        [ 69,  94, 120],
        [ 66,  91, 117],
        ...,
        [ 38,  13,   9],
        [ 35,  10,   6],
        [ 32,  10,   5]],

       [[ 57,  81, 109],
        [ 56,  81, 107],
        [ 57,  81, 109],
        ...,
        [ 44,  19,  15],
        [ 38,  16,  11],
        [ 35,  13,   8]],

       [[ 52,  76, 106],
        [ 53,  77, 105],
        [ 56,  80, 110],
        ...,
        [ 39,  17,  12],
        [ 33,  13,   8],
        [ 31,  11,   6]],

       ...,

       [[ 71,  87,  94],
        [ 69,  85,  92],
        [ 69,  85,  92],
        ...,
        [ 45,  57,  61],
        [ 45,  57,  61],
        [ 47,  59,  63]],

       [[ 72,  87,  96],
        [ 72,  87,  96],
        [ 71,  88,  97],
        ...,
        [ 45,  56,  60],
        [ 44,  55,  59],
        [ 47,  58,  62]],

       [[ 75,  90,  99],
        [ 76,  91, 100],
        [ 77,  94, 103],
        ...,
        [ 49,  60,  64],
        [ 48,  59,  63],
        [ 50,  61,  65]]

In [10]:
# to fraw a rectangle
cv2.rectangle(image, rand_pt(), rand_pt(), (255, 0, 0), 3)

array([[[ 72,  97, 123],
        [ 69,  94, 120],
        [ 66,  91, 117],
        ...,
        [ 38,  13,   9],
        [ 35,  10,   6],
        [ 32,  10,   5]],

       [[ 57,  81, 109],
        [ 56,  81, 107],
        [ 57,  81, 109],
        ...,
        [ 44,  19,  15],
        [ 38,  16,  11],
        [ 35,  13,   8]],

       [[ 52,  76, 106],
        [ 53,  77, 105],
        [ 56,  80, 110],
        ...,
        [ 39,  17,  12],
        [ 33,  13,   8],
        [ 31,  11,   6]],

       ...,

       [[ 71,  87,  94],
        [ 69,  85,  92],
        [ 69,  85,  92],
        ...,
        [ 45,  57,  61],
        [ 45,  57,  61],
        [ 47,  59,  63]],

       [[ 72,  87,  96],
        [ 72,  87,  96],
        [ 71,  88,  97],
        ...,
        [ 45,  56,  60],
        [ 44,  55,  59],
        [ 47,  58,  62]],

       [[ 75,  90,  99],
        [ 76,  91, 100],
        [ 77,  94, 103],
        ...,
        [ 49,  60,  64],
        [ 48,  59,  63],
        [ 50,  61,  65]]

In [11]:
cv2.imshow('image',image)

In [12]:
width, height = 128, 256
resized_image = cv2.resize(image, (width, height))
print("resized image shape:", resized_image.shape)

resized image shape: (256, 128, 3)


In [17]:
# reading a Video in Open CV
video = cv2.VideoCapture("D:/Pics Me/Suppu Phone/117APPLE/IMG_7043.MOV")

In [18]:
while True:
    has_frame, frame = video.read()
    if not has_frame:
        print('Reached the end of the video')
        break
        
    cv2.imshow('frame', frame)
    key = cv2.waitKey(50)
    if key == 27:
        print("Pressed Esc")
        break
cv2.destroyAllWindows()

Pressed Esc


In [19]:
import numpy
import cv2

def print_capture_properties(*args):
    capture = cv2.VideoCapture(*args)
    print('Created capture:', ' '.join(map(str, args)))
    print('Frame count:', int(capture.get(cv2.CAP_PROP_FRAME_COUNT)))
    print('Frame width:', int(capture.get(cv2.CAP_PROP_FRAME_WIDTH)))
    print('Frame height:', int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
    print('Frame rate:', capture.get(cv2.CAP_PROP_FPS))

In [20]:
print_capture_properties("D:/Pics Me/Suppu Phone/117APPLE/IMG_7043.MOV")

Created capture: D:/Pics Me/Suppu Phone/117APPLE/IMG_7043.MOV
Frame count: 336
Frame width: 1920
Frame height: 1080
Frame rate: 29.977695167286246


In [21]:
print_capture_properties(0)

Created capture: 0
Frame count: -1
Frame width: 640
Frame height: 480
Frame rate: 30.0


###  Writing a Frame Stream in to a video

In [1]:
#creating camera capture object
import cv2
capture = cv2.VideoCapture(0)
frame_width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
print('Frame width:', frame_width)
print('Frame height:', frame_height)


Frame width: 640
Frame height: 480


In [2]:
# creating a video writer
video = cv2.VideoWriter('../data/captured_video.avi', cv2.VideoWriter_fourcc(*'X264'),
                        25, (frame_width, frame_height))

##### capture frames in while loop and write in video.write

In [3]:
while True:
    has_frame, frame = capture.read()
    if not has_frame:
        print('Can\'t get frame')
        break
        
    video.write(frame)
        
    cv2.imshow('frame', frame)
    key = cv2.waitKey(3)
    if key == 27:
        print('Pressed Esc')
        break
        

Pressed Esc


In [4]:
capture.release()
#writer.release()
cv2.destroyAllWindows()